name: "PR Kind Labeler"
description: "Sync /kind commands in PR body to GitHub labels and enforce changelog notes"
inputs:
  token:
    description: "GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT)"
    default: ${{ github.token }}
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.token }}
