name: labeler

on:
  pull_request:
    types: [opened, edited, reopened]

permissions:
  issues: write
  contents: write
  pull-requests: write

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - uses: ./
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
